/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Vector;
import javafx.scene.control.CheckBox;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Position;

/**
 *
 * @author thiag
 */
public class TicketReservation extends javax.swing.JInternalFrame {

    /**
     * Creates new form TicketReservation
     */
    public TicketReservation() {
        initComponents();
        try{
            setSelected(true);   
            setMaximizable(true);   
            setMaximum(true);
        }catch(Exception e){
        }
        price = 0.00;
        pricelbl.setText("R$ " + price);
        
        dtmFlights = (DefaultTableModel) flightTable.getModel();
        for(int i = 0; i < TelaPrincipal.airport.numOfAirplanes(); i++){
            dtmFlights.addRow(TelaPrincipal.airport.getAirplane(i).toString().split("\t"));
        }
        
        modelo = new DefaultListModel();
        seatList.setModel(modelo);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        flightPanel = new javax.swing.JPanel();
        toClass = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        classPanel = new javax.swing.JPanel();
        backToFlight = new javax.swing.JButton();
        firstClass = new javax.swing.JButton();
        economicClass = new javax.swing.JButton();
        seatPanel = new javax.swing.JPanel();
        toPayment = new javax.swing.JButton();
        backToClass = new javax.swing.JButton();
        seatGrid = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        seatList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        pricelbl = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        backToSeat = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        boardingPanel = new javax.swing.JPanel();
        backToStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        voolbl = new javax.swing.JLabel();
        destinolbl = new javax.swing.JLabel();
        horariolbl = new javax.swing.JLabel();
        assentoslbl = new javax.swing.JLabel();
        portaolbl = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);

        jTabbedPane1.setBackground(new java.awt.Color(220, 220, 220));
        jTabbedPane1.setEnabled(false);

        toClass.setText("Próximo");
        toClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Companhia", "Voo", "Partida", "Destino", "Portão"
            }
        ));
        flightTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(flightTable);

        javax.swing.GroupLayout flightPanelLayout = new javax.swing.GroupLayout(flightPanel);
        flightPanel.setLayout(flightPanelLayout);
        flightPanelLayout.setHorizontalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toClass)
                .addGap(33, 33, 33))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(flightPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        flightPanelLayout.setVerticalGroup(
            flightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toClass)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Escolher Voo", flightPanel);

        backToFlight.setText("Voltar");
        backToFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToFlightActionPerformed(evt);
            }
        });

        firstClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstClass.setText("Primeira Classe");
        firstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassActionPerformed(evt);
            }
        });

        economicClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        economicClass.setText("Classe Econômica");
        economicClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economicClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(backToFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(economicClass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstClass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(firstClass)
                .addGap(43, 43, 43)
                .addComponent(economicClass)
                .addGap(208, 208, 208)
                .addComponent(backToFlight)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Escolha uma classe", classPanel);

        toPayment.setText("Próximo");
        toPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPaymentActionPerformed(evt);
            }
        });

        backToClass.setText("Voltar");
        backToClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seatGridLayout = new javax.swing.GroupLayout(seatGrid);
        seatGrid.setLayout(seatGridLayout);
        seatGridLayout.setHorizontalGroup(
            seatGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        seatGridLayout.setVerticalGroup(
            seatGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(seatList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Preço:");

        pricelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pricelbl.setText("R$ 0,00");

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatPanelLayout.createSequentialGroup()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(backToClass, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addComponent(toPayment))
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pricelbl))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatPanelLayout.createSequentialGroup()
                    .addContainerGap(187, Short.MAX_VALUE)
                    .addComponent(seatGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pricelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toPayment)
                    .addComponent(backToClass))
                .addGap(25, 25, 25))
            .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seatPanelLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(seatGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Escolha um assento", seatPanel);

        finish.setText("Concluir");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        backToSeat.setText("Voltar");
        backToSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToSeatActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Cartão de Crédito");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/creditcard.png"))); // NOI18N

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(backToSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(finish)
                .addGap(25, 25, 25))
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jRadioButton1)
                        .addGap(57, 57, 57))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finish)
                    .addComponent(backToSeat))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Escolha uma opção de pagamento", paymentPanel);

        backToStart.setText("Nova Operação");
        backToStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToStartActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Nome do Passageiro: ");

        jLabel5.setText("Voo: ");

        jLabel6.setText("Destino: ");

        jLabel7.setText("Saída: ");

        jLabel8.setText("Assentos: ");

        jLabel9.setText("Portão: ");

        destinolbl.setText("---");

        horariolbl.setText("jLabel10");

        assentoslbl.setText("jLabel10");

        portaolbl.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(destinolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(assentoslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(portaolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(voolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(horariolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(183, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(assentoslbl)
                    .addComponent(destinolbl))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(portaolbl))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(voolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addComponent(jLabel6)
                    .addGap(49, 49, 49)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(horariolbl))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout boardingPanelLayout = new javax.swing.GroupLayout(boardingPanel);
        boardingPanel.setLayout(boardingPanelLayout);
        boardingPanelLayout.setHorizontalGroup(
            boardingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardingPanelLayout.createSequentialGroup()
                .addGroup(boardingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardingPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backToStart))
                    .addGroup(boardingPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        boardingPanelLayout.setVerticalGroup(
            boardingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardingPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(backToStart)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Cartão de embarque", boardingPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toClassActionPerformed
        int selectedRow = flightTable.getSelectedRow();
        if(selectedRow >= 0){
            airplane = TelaPrincipal.airport.getAirplane(selectedRow);
            jTabbedPane1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_toClassActionPerformed

    private void toPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPaymentActionPerformed
        jTabbedPane1.setSelectedIndex(3);        // TODO add your handling code here:
    }//GEN-LAST:event_toPaymentActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        String seats = "";
        for(int i = 0; i< seatList.getModel().getSize();i++){
            String seat = seatList.getModel().getElementAt(i);
            airplane.reserveSeat(LoginScreen.user, seat);
            seats += " - ";
            seats += seat;
        }
        assentoslbl.setText(seats);
        portaolbl.setText(""+airplane.gate);
        destinolbl.setText(airplane.destination);
        horariolbl.setText(airplane.departureTime);
        voolbl.setText(""+airplane.flight);
        nome.setText(LoginScreen.user.getName());
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_finishActionPerformed

    private void backToFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToFlightActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_backToFlightActionPerformed

    private void backToClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToClassActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_backToClassActionPerformed

    private void backToSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToSeatActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_backToSeatActionPerformed

    private void backToStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToStartActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_backToStartActionPerformed

    private void economicClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economicClassActionPerformed
        seatGrid.removeAll();
        chooseSeat(2);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_economicClassActionPerformed

    private void firstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassActionPerformed
        seatGrid.removeAll();
        chooseSeat(1);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_firstClassActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    private void chooseSeat(int option){
        seatGrid.setLayout(new GridLayout(airplane.numberOfRows, 6));
        
        for(int i = 0; i < airplane.numberOfRows; i++){
            for(int j = 0; j < 6; j++){
                if(option == 1){
                    if(i < airplane.first.rows.length){
                        Seat seat = airplane.first.rows[i].seats[j];
                        javax.swing.JToggleButton seatButton = seat.seat;
                        seatGrid.add(seatButton);
                        seatButton.addActionListener(tratadorEvento);
                        seatButton.setActionCommand(seat.name);
                    }else{
                        javax.swing.JToggleButton seatButton = new javax.swing.JToggleButton(i+1 + Seat.converteToString(j));
                        seatGrid.add(seatButton);
                        seatButton.setEnabled(false);
                    }
                }else if(option == 2){
                    if(i < airplane.first.rows.length){
                        javax.swing.JToggleButton seatButton = new javax.swing.JToggleButton(i+1 + Seat.converteToString(j));
                        seatGrid.add(seatButton);
                        seatButton.setEnabled(false);
                    }else{
                        int x = i - 5;
                        Seat seat = airplane.economic.rows[x].seats[j];
                        javax.swing.JToggleButton seatButton = seat.seat;
                        seatGrid.add(seatButton);
                        seatButton.addActionListener(tratadorEvento);
                        seatButton.setActionCommand(seat.name);
                    }
                }else{}
            }
        }
    }
    
    private ActionListener tratadorEvento = new ActionListener() {

        public void actionPerformed(ActionEvent ae) {
            
            String nameButton = ae.getActionCommand();
            if(seatList.getModel().getSize() != 0){ //If list is not empty
                int index = seatList.getNextMatch(nameButton, 0, Position.Bias.Forward);
                if (index != -1){
                    modelo.remove(index);
                    price = price - airplane.findSeat(nameButton).price;
                    pricelbl.setText("R$ " + price);
                }else{
                    modelo.addElement(nameButton);
                    price = price + airplane.findSeat(nameButton).price;
                    pricelbl.setText("R$ " + price);
                }    
            }else{
                modelo.addElement(nameButton);
                price = price + airplane.findSeat(nameButton).price;
                pricelbl.setText("R$ " + price);
            }
            
        }
    };
    
    private double price;
    private DefaultListModel modelo;
    public static Airplane airplane;
    private final DefaultTableModel dtmFlights;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assentoslbl;
    private javax.swing.JButton backToClass;
    private javax.swing.JButton backToFlight;
    private javax.swing.JButton backToSeat;
    private javax.swing.JButton backToStart;
    private javax.swing.JPanel boardingPanel;
    private javax.swing.JPanel classPanel;
    private javax.swing.JLabel destinolbl;
    private javax.swing.JButton economicClass;
    private javax.swing.JButton finish;
    private javax.swing.JButton firstClass;
    private javax.swing.JPanel flightPanel;
    private javax.swing.JTable flightTable;
    private javax.swing.JLabel horariolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel portaolbl;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JPanel seatGrid;
    private javax.swing.JList<String> seatList;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JButton toClass;
    private javax.swing.JButton toPayment;
    private javax.swing.JLabel voolbl;
    // End of variables declaration//GEN-END:variables
}
